<div style="padding:20px; 
            height: 30px;
            width: 500px;
            color:#36FF00;
            margin:10px;
            font-size:110%;
            display:fill;
            border-radius:10px;
            border-style: solid;
            border-color: #36FF00;
            background-color:#000000;
            overflow:hidden;
            font-weight:500">
            Numpy
            </div>

Numerical Python Package

<code style="background:yellow;color:red">Numerical Python Package</code>

<code style="background:red;color:white">
Let's Go!
</code>

In [2]:
import numpy as np

<code style="background:yellow;color:red">Numpy Array - ndarray</code>

The whole NumPy library is based on one main object: ndarray (which stands for N-dimensional array).
This object is a multidimensional homogeneous array with a predetermined number of items:
homogeneous because virtually all the items within it are of the same type and the same size. In fact, the
data type is specified by another NumPy object called dtype (data-type); each ndarray is associated with
only one type of dtype.

The number of the dimensions and items in an array is defined by its shape, a tuple of N-positive
integers that specifies the size for each dimension. The dimensions are defined as axes and the number of
axes as rank.

Moreover, another peculiarity of NumPy arrays is that their size is fixed, that is, once you defined their
size at the time of creation, it remains unchanged. This behavior is different from Python lists, which can
grow or shrink in size.

To define a new ndarray, the easiest way is to use the array() function, passing a Python list containing
the elements to be included in it as an argument.

In [3]:
liste = [10,20,30,40,50]

In [4]:
type(liste)

list

In [5]:
#listeyi np array'e çevirmek

np.array(liste)

array([10, 20, 30, 40, 50])

In [6]:
type(np.array(liste))

numpy.ndarray

In [7]:
np.array(liste).dtype

dtype('int64')

In [8]:
matrix_list = [[10,20,30],[20,30,40],[30,40,50]]  #listenin içerisinde liste

In [9]:
type(matrix_list)

list

In [10]:
#convert to ndarray

np.array(matrix_list)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [11]:
# use the ndim attribute for getting the axes, the size attribute to know the array length, and the shape attribute to get its shape.

x =np.array(matrix_list)

In [12]:
x.ndim # kaç boyutlu olduğunu verir

2

In [13]:
x.size # kaç eleman olduğunu verir

9

In [57]:
x.shape # kaç satır kaç sütun olduğunu verir

(3, 3)

In [55]:
x.itemsize #her bir elemanın byte cinsinden boyutu

8

In [56]:
x.data #verilerin bellekteki yeri

<code style="background:yellow;color:red">Numpy Methods</code>

<code style="background:red;color:white">
arange
</code>

In [15]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,20,2) #with step size

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

<code style="background:red;color:white">
zeros
</code>

In [18]:
np.zeros(5)  #içinde 5 tane sıfır olan dizi oluşturur

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((7,7)) #tuple olarak arg verilir matris oluşturulur

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

<code style="background:red;color:white">
ones
</code>

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<code style="background:red;color:white">
linspace
</code>

belirtiğiniz rakamlar arasında evenly spaced, eşit aralıklarda boyutlandırılmış bir dizi oluşturur

In [22]:
np.linspace(0,20,5) #0 ila 20 arasında 5 eşit mesafe bırakarak bir dizi oluştur

array([ 0.,  5., 10., 15., 20.])

In [23]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

<code style="background:red;color:white">
linspace
</code>

identity matrix oluşturur

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<code style="background:red;color:white">
random
</code>

normal standart distroya uygun veriler çıkartıyor

In [25]:
np.random.randn(7) # 

array([-0.73942384,  0.24048557,  0.14371247, -2.19977766, -1.73522096,
        0.21620721, -1.82833677])

In [28]:
np.random.randn(5,5)

array([[-1.83353901, -1.01588947, -0.3401797 , -0.34482407,  0.71024297],
       [-0.91644127,  0.2758519 , -0.37442365,  0.37145642, -0.97441234],
       [ 0.54267082,  0.51465612,  0.65968139, -0.36628379, -0.70345009],
       [ 1.68015571, -0.41467966, -0.1429533 , -1.35038459, -0.41100808],
       [ 1.15871781,  0.61921619, -0.37572238, -0.43837383, -0.39648745]])

In [29]:
np.random.randint(1,10) #1 ile 10 arasında rastgele bir sayı üretir

5

In [31]:
np.random.randint(1,10,5) #1 ile 10 arasında 5 tane rastgele sayı üretir

array([9, 1, 8, 4, 2])

In [33]:
np.random.randint(1,30,(3,3)) #1 ile 300 arasında 3x3 lük bir matris oluşturur

array([[27, 14,  7],
       [26, 21,  6],
       [13, 14,  2]])

In [34]:
dizi = np.arange(30)
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
random_dizi = np.random.randint(0,100,30)

random_dizi


array([89, 65, 60, 40,  7, 21, 82, 23, 63, 39, 26, 45, 53,  4, 19, 98, 52,
        8, 27, 76, 32, 76, 30, 23, 29, 16, 23, 49, 50, 49])

<code style="background:red;color:white">
numpy array methods - numpy dizi methodları
</code>

In [38]:
r_dizi = np.random.randint(0,100,20)

r_dizi

array([13, 61, 56, 85, 33, 48, 33, 20, 55, 60, 89, 29, 62, 23, 85, 68, 64,
       66, 54, 84])

In [40]:
dizi = np.arange(0,30)

dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [42]:
dizi.reshape(5,6) #5x6 lık bir matris oluşturur

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
dizi.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [44]:
r_dizi.max() #en büyük elemanı verir

89

In [45]:
r_dizi.min() #en küçük elemanı verir


13

In [46]:
r_dizi.argmax() #en büyük elemanın indexini verir

10

In [47]:
r_dizi.argmin() #en küçük elemanın indexini verir

0

In [50]:
dizi.shape #reshape orijinal diziyi değiştirmez

(30,)

In [51]:
reshape_dizi = dizi.reshape(5,6)

In [53]:
reshape_dizi.shape

(5, 6)

<code style="background:red;color:white">
numpy indices
</code>

In [59]:
import numpy as np


In [60]:
dizi1 = np.arange(0,15)

In [61]:
dizi1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

<code style="background:red;color:white">
numpy array methods - numpy dizi methodları
</code>

In [66]:
dizi1[3:8] = -7 #3 ile 8 arasındaki elemanları -7 yapar

dizi1

array([ 0,  1,  2, -7, -7, -7, -7, -7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
dizi2 = np.arange(0,24)

In [70]:
dizi2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
sliced_and_diced = dizi2[4:9]

In [73]:
sliced_and_diced

array([4, 5, 6, 7, 8])

In [74]:
dizi2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
sliced_and_diced[:]= 111

In [76]:
sliced_and_diced

array([111, 111, 111, 111, 111])

In [78]:
dizi2 #sliced_and_diced değişiklikleri dizi2'ye de yansır, subsetting işlemi referans üzerinden çalışır, bütün değişiklikler orijinal diziyi etkiler

array([  0,   1,   2,   3, 111, 111, 111, 111, 111,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [79]:
dizi3 = np.arange(0,24)

In [80]:
Kopya_dizi3 = dizi3.copy() #dizinin kopyasını oluşturur

In [81]:
Kopya_dizi3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
slice_kopya = Kopya_dizi3[3:7]

In [83]:
slice_kopya

array([3, 4, 5, 6])

In [84]:
slice_kopya[:]= 333

In [85]:
slice_kopya

array([333, 333, 333, 333])

In [86]:
Kopya_dizi3

array([  0,   1,   2, 333, 333, 333, 333,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [88]:
dizi3  #orijinal dizi üzerinde değişiklik yapılmadan, dizi üzerinde işlemler yapmak için copy() metodu kullanılır. dizinin kopyası alındıktan sonra işlemler yapılır

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

<code style="background:red;color:white">
matrix indices
</code>

In [89]:
matrix_list = [[10,20,30],[20,30,40],[30,40,50]]  #listenin içerisinde liste

In [90]:
npmatriks = np.array(matrix_list)
npmatriks

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [91]:
npmatriks[0] #0. satırı verir

array([10, 20, 30])

In [93]:
npmatriks[1][2] #1. satır 2. sütun


40

In [94]:
npmatriks[1,2] #1. satır 2. sütun

40

In [95]:
npmatriks[1:,2] #1. satırdan sonrası 2. sütun


array([40, 50])

In [96]:
npmatriks[2:,2]

array([50])

In [99]:
npmatriks[0:,1] #tüm satırların 1. sütunu

array([20, 30, 40])

In [102]:
npmatriks[2:,1] #2. satırdan sonrası 1. sütun

array([40])

In [107]:
liste1 = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [108]:
matrx = np.array(liste1)

In [109]:
matrx

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [110]:
matrx[2]

array([10, 11, 12, 13, 14])

In [114]:
#FANCY INDEXING
matrx[[0,2,4]] #0,2,4. satırları getirir, fancy indexing

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [115]:
matrx[[4,2,1]] #4,2,1. satırları getirir

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

In [117]:
matrx[[0,2,4],[0,2,4]] # 0. satır 0. sütun, 2. satır 2. sütun, 4. satır 4. sütun

array([ 0, 12, 24])

<code style="background:red;color:white">
numpy dizilerinde operasyonlar
</code>

In [118]:
dizi4 = np.arange(5,25)

dizi4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [120]:
dizi4[dizi4>10] #10'dan büyük elemanları getirir

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [122]:
dizi5= np.random.randint(1,100,20)

dizi5

array([41, 14, 84, 37, 31, 93, 89, 48, 32, 87, 83, 17, 10, 24, 71, 51, 84,
       24, 68, 79])

In [124]:
dizi5>24

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True, False,
        True,  True])

In [123]:
dizi5[dizi5>24]

array([41, 84, 37, 31, 93, 89, 48, 32, 87, 83, 71, 51, 84, 68, 79])

In [126]:
dizi6 = np.arange(0,24)
dizi6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [127]:
dizi6 + dizi6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [131]:
dizi6 #dizi üzerinde değişiklik yapmaz, sadece işlemi yapar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [129]:
dizi6 * dizi6

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [132]:
dizi6 - dizi6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [133]:
dizi6 / dizi6 #0/0 = nan

/tmp/ipykernel_15245/1375907252.py:1: RuntimeWarning: invalid value encountered in divide
  dizi6 / dizi6 #0/0 = nan


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [134]:
dizi6 ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [135]:
np.sqrt(dizi6)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [136]:
np.max(dizi6)

23

In [137]:
np.min(dizi6)

0